= Principales aportaciones <principales-aportaciones>

Teniendo en cuenta los objetivos que se han establecido al principio de este TFG, los cuales se encuentran en la sección de Objetivos, las principales aportaciones que se proporcionan son las siguientes:

+ *Evidencia práctica sobre la compatibilidad entre datos _in situ_ y datos remotos de menor resolución para la estimación de biodiversidad del suelo:* la integración y armonización de las mediciones de campo de alta calidad del proyecto SOB4ES con fuentes remotas de acceso abierto (Google Earth Engine y Copernicus) aporta un punto de comparación adicional a la evidencia ya existente sobre si los datos _in situ_ siguen ofreciendo una ventaja informativa frente a los derivados exclusivamente de fuentes satelitales y estaciones climáticas (véase #link(<antecedentes-y-contexto>)[*Antecedentes y contexto*]), además de un proceso de armonización documentado que podría reutilizarse con otros grupos de especies o campañas de muestreo del proyecto europeo. Esta aportación da respuesta directa al primer y segundo objetivo específico planteados en este trabajo (véase #link(<objetivos>)[*Objetivos*]), centrados respectivamente en la integración de los datos del proyecto SOB4ES con fuentes externas y en su posterior armonización en un conjunto consistente.

+ *Justificación metodológica de qué técnicas de aprendizaje automático son adecuadas para las características concretas de este problema:* la selección de algoritmos (regresión regularizada, ensamblados basados en árboles y redes neuronales) se ha justificado explícitamente en función de las limitaciones del problema, tamaño muestral reducido e indicadores de salida potencialmente correlacionados entre sí, en lugar de partir de una elección arbitraria o exhaustiva de algoritmos. Con ello se da cumplimiento al tercer objetivo específico (véase #link(<objetivos>)[*Objetivos*]), relativo a la selección y justificación metodológica de las técnicas de análisis y aprendizaje automático más adecuadas al problema.

+ *Evidencia empírica sobre qué familia de algoritmos generaliza mejor en la predicción de biodiversidad del suelo con un conjunto de datos reducido:* la comparación sistemática de regresión _Ridge_, _Random Forest_, XGBoost, RegressorChain y redes neuronales MLP bajo un mismo marco de validación cruzada repetida y una misma partición estricta de entrenamiento, validación y evaluación permite contrastar empíricamente, con datos propios, la hipótesis recurrente en la literatura revisada de que los modelos basados en árboles igualan o superan a las redes neuronales cuando el conjunto de datos es pequeño. Esta comparación sistemática responde al cuarto objetivo específico (véase #link(<objetivos>)[*Objetivos*]), orientado a entrenar, comparar y evaluar distintos algoritmos de aprendizaje automático supervisado para aislar la solución más precisa, robusta y con mayor capacidad de generalización.

+ *Evaluación de si el modelado conjunto (multi-salida) aporta ventaja frente al modelado independiente por indicador:* al entrenar variantes multi-salida (rf_multisalida, xgb_multisalida, mlp_multisalida, regressorchain) junto con sus equivalentes de salida única bajo las mismas condiciones, este trabajo aporta evidencia sobre si aprovechar las relaciones entre distintos indicadores de biodiversidad del suelo mejora o no las predicciones frente a tratarlos de forma independiente, una pregunta que la literatura revisada no responde de forma directa para este dominio. 
  
  A esto se suma el resultado de la prueba de eliminación de variables sobre la relevancia real de los micronutrientes del suelo: la evaluación sistemática del efecto de eliminar cu_z, ni_z y mo_z, de forma individual y combinada, aporta evidencia sobre si estas variables son realmente necesarias para la predicción o si su contribución es redundante frente al resto de variables climáticas y edáficas empleadas. Dichos resultados se pueden ver con más detalle en el #link(<pruebas-llevadas-a-cabo>)[*Anexo V*], y la interpretación conjunta de todas las pruebas realizadas se recoge en la #link(<discusion-general>)[*Discusión general (Anexo V)*]. Ambos análisis se enmarcan igualmente en el cuarto objetivo específico (véase #link(<objetivos>)[*Objetivos*]), al aportar evidencia adicional sobre la robustez y la capacidad de generalización de las distintas configuraciones de modelos evaluadas.

+ *Aplicación de una metodología de gestión de proyectos de ciencia de datos como marco de rigor metodológico:* el uso sistemático de CRISP-ML(Q) a lo largo de este trabajo ha permitido anticipar y mitigar riesgos habituales en estudios de este tipo, como por ejemplo, el sobreajuste con conjuntos de datos reducidos, fuga de información entre las fases de entrenamiento y evaluación, entre otros, mediante decisiones metodológicas concretas (partición estricta de datos, validación cruzada repetida), que quedan documentadas y podrían servir de referencia para futuros trabajos de investigación dentro del propio proyecto SOB4ES. De este modo se satisface el quinto y último objetivo específico (véase #link(<objetivos>)[*Objetivos*]), centrado en garantizar el rigor metodológico y la reproducibilidad de los resultados obtenidos a lo largo de todo el proceso de investigación.
