= Principales aportaciones <principales-aportaciones>

Teniendo en cuenta los objetivos que se han establecido al principio de este TFG, los cuales se encuentran en la sección de Objetivos, las principales aportaciones que se proporcionan son las siguientes:

+ *Evidencia práctica sobre la compatibilidad entre datos _in situ_ y datos remotos de menor resolución para la estimación de biodiversidad del suelo:* la integración y armonización de las mediciones de campo de alta calidad del proyecto SOB4ES con fuentes remotas de acceso abierto (Google Earth Engine y Copernicus) aporta un punto de comparación adicional a la evidencia ya existente sobre si los datos _in situ_ siguen ofreciendo una ventaja informativa frente a los derivados exclusivamente de fuentes satelitales y estaciones climáticas (véase #link(<antecedentes-y-contexto>)[*Antecedentes y contexto*]), además de un proceso de armonización documentado que podría reutilizarse con otros grupos de especies o campañas de muestreo del proyecto europeo.

+ *Justificación metodológica de qué técnicas de aprendizaje automático son adecuadas para las características concretas de este problema:* la selección de algoritmos (regresión regularizada, ensamblados basados en árboles y redes neuronales) se ha justificado explícitamente en función de las limitaciones del problema, tamaño muestral reducido e indicadores de salida potencialmente correlacionados entre sí, en lugar de partir de una elección arbitraria o exhaustiva de algoritmos.

+ *Evidencia empírica sobre qué familia de algoritmos generaliza mejor en la predicción de biodiversidad del suelo con un conjunto de datos reducido:* la comparación sistemática de regresión Ridge, Random Forest, XGBoost, RegressorChain y redes neuronales MLP bajo un mismo marco de validación cruzada repetida y una misma partición estricta de entrenamiento, validación y evaluación permite contrastar empíricamente, con datos propios, la hipótesis recurrente en la literatura revisada de que los modelos basados en árboles igualan o superan a las redes neuronales cuando el conjunto de datos es pequeño.

+ *Evaluación de si el modelado conjunto (multi-salida) aporta ventaja frente al modelado independiente por indicador:* al entrenar variantes multi-salida (rf_multisalida, xgb_multisalida, mlp_multisalida, regressorchain) junto con sus equivalentes de salida única bajo las mismas condiciones, este trabajo aporta evidencia sobre si aprovechar las relaciones entre distintos indicadores de biodiversidad del suelo mejora o no las predicciones frente a tratarlos de forma independiente, una pregunta que la literatura revisada no responde de forma directa para este dominio. 
  
  A esto se suma el resultado de la prueba de eliminación de variables sobre la relevancia real de los micronutrientes del suelo: la evaluación sistemática del efecto de eliminar cu_z, ni_z y mo_z, de forma individual y combinada, aporta evidencia sobre si estas variables son realmente necesarias para la predicción o si su contribución es redundante frente al resto de variables climáticas y edáficas empleadas. Dichos resultados se pueden ver con más detalle en el #link(<pruebas-llevadas-a-cabo>)[*Anexo V*].

+ *Aplicación de una metodología de gestión de proyectos de ciencia de datos como marco de rigor metodológico:* el uso sistemático de CRISP-ML(Q) a lo largo de este trabajo ha permitido anticipar y mitigar riesgos habituales en estudios de este tipo, como por ejemplo, el sobreajuste con conjuntos de datos reducidos, fuga de información entre las fases de entrenamiento y evaluación, entre otros, mediante decisiones metodológicas concretas (partición estricta de datos, validación cruzada repetida), que quedan documentadas y podrían servir de referencia para futuros trabajos de investigación dentro del propio proyecto SOB4ES.
