= Antecedentes y contexto <antecedentes-y-contexto>

El proyecto europeo SOB4ES, en cuyo marco se desarrolla este TFG, surge como respuesta a la necesidad de la Unión Europea de contar con indicadores fiables y de bajo coste sobre la biodiversidad del suelo, en contexto de la Estrategia de Suelos de la UE (EU Soil Strategy). Tradicionalmente, la evaluación de la biodiversidad edáfica se ha basado en muestreos de campo y análisis de laboratorio, que si bien son precisos, presentan las limitaciones ya descritas en la Introducción: coste elevado, falta de estandarización metodológica entre grupos y especies y dificultad para escalar todo a nivel continental o internacional.

Ante estas limitaciones, en los últimos años se han extendido el uso de modelos de aprendizaje automático supervisado para estimar indicaciones ambientales y de biodiversidad a partir de variables predictoras más económicas de obtener (datos climáticos, satelitales y edafológicos), reduciendo así la dependencia de mediciones directa exhaustivas sobre el terreno.

Varios trabajos han abordado directamente el modelado de biodiversidad del suelo haciendo uso del aprendizaje automático, con resultados que nos pueden servir de referencia para contrastar con los resultados obtenidos en este TFG (véase *@conclusiones*):
+ Salako et al.#sub([@salakoEarthworms]) emplearon *Random Forest* para modelar la distribución espacial de la riqueza y densidad (ind./m²) de tres grupos ecológicos de lombrices (epigeas, endogeas y anécicas) en Alemania, usando como predictores variables de suelo y clima a distintos usos del terreno.

 Encontraron que cada grupo ecológico responde a predictores distintos: las especies epigeas están mayoritariamente condicionadas por el clima en zonas forestales, mientras que las endogeas, el grupo más diverso, dependen sobre todo de la textura del suelo (contenido de arcilla y limo).

+ Un estudio de modelado conjunto multiespecie#sub([@diggingDeeperEarthworms]) entrenó una *red neuronal profunda multi-tarea* para predecir la distribución de 77 especies de lombrices en Francia a partir de variables climáticas, edáficas y de cobertura del terreno, empleando SHAP para identificar los principales factores ambientales. El modelo conjunto alcanzó un TSS ≥ 0.7 y mejoró notablemente las predicciones para especies raras frente a los modelos de distribución de especies tradicionales (de una sola especie).

+ Un estudio sobre biodiversidad multi-trófica del suelo mediante metabarcoding de ADN ambiental #sub([@limitsPromisesEOFoundationModels]) comparó sistemáticamente *LightGBM, Random Forest y una red neuronal (ANN)* para predecir la abundancia relativa de 51 grupos tróficos (bacterias, hongos, protistas, oligoquetos, insectos, colémbolos y otros metazoos), usando cuatro configuraciones de variables predictoras: datos ambientales de baja resolución, datos in situ de alta calidad, embeddings de imágenes satelitales, y una combinación de ambos. 

 Random Forest obtuvo consistentemente el mejor rendimiento, ligeramente por encima de LightGBM, y los datos in situ de alta calidad superaron sistemáticamente tanto a los datos de baja resolución como a los derivados de imágenes satelitales. Un resultado directamente relevante para este TFG, que también combina variables in situ (SOB4ES) con variables remotas de menor resolución (Google Earth Engine, Copernicus).

+ Un estudio de predicción del microbioma del suelo#sub([@soilMicrobiomePrediction]) comparó seis modelos de aprendizaje automático clásico (incluyendo Random Forest y Gradient Boosting) frente a un modelo de aprendizaje profundo para predecir la frecuencia relativa de comunidades bacterianas y fúngicas a partir de factores ambientales.

  *Gradient Boosting* obtuvo el mejor resultado a nivel de filo (R² = 0.57), y Random Forest y Gradient Boosting empataron como mejores modelos a nivel de grupo funcional (R² = 0.45); las arquitecturas más sofisticadas de aprendizaje profundo (CNN, transformers) obtuvieron resultados peores, atribuido explícitamente al tamaño reducido de los datos de entrenamiento disponibles. Esto es una conclusión especialmente relevante para este TFG, cuyo conjunto de datos (~400 muestras) es de un orden de magnitud similar.

En conjunto, estos antecedentes apuntan de forma consistente a que los modelos basados en árboles, como Random Forest, Gradient Boosting y XGBoost, pueden igualar o hasta superar a los modelos basados en redes neuronales cuando el conjunto de datos, especialmente en el caso de los datos relacionados con la biodiversidad (que son reducidos) y a que los datos in situ de alta calidad siguen siendo, por ahora, más informativos que los derivados exclusivamente de fuentes remotas con resoluciones bajas. Estas dos hipótesis pueden ser contrastadas empíricamente con los resultados de esta TFG.

Este enfoque indirecto no es exclusivo de la biodiversidad del suelo. El uso de variables climáticas, satelitales y edáficas como predictoras de propiedades del ecosistema está ya consolidado en ámbitos afines, de los cuales se resaltan los siguientes:\
- Estimación del carbono orgánico en el suelo.
- Clasificación de usos del terreno.
- Predicción del rendimiento agrícola a partir de series temporales de NDVI.
La disponibilidad reciente de catálogos satelitales abiertos de alta resolución y de reanálisis climáticos globales, ha reducido significativamente la barrera de entrada para poder aplicar estas técnicas a nuevos problemas ecológicos, entre los cuales se encuentra el que aborda en este TFG.

Frente a estos antecedentes, la aportación diferencial que puede proporcionar este TFG es doble: por un lado, la integración de múltiples fuentes de orígenes heterogéneos en un mismo pipeline reproducible y versionado; por otro lado la comparación de múltiples algoritmos de aprendizaje supervisado bajo un mismo marco de validación, en lugar de limitarse a un único modelo, lo que permite discutir con evidencia empírica cuál generaliza mejor mejor ante un conjunto de datos comparativamente reducido.

Este TFG se sitúa bajo el contexto siguiente: parte de los datos previamente recolectados por el proyecto SOB4ES en más de 400 puntos geográficos europeos, y los complementa con fuentes de datos remotas de acceso abierto, con el objetivo de evaluar hasta qué punto los modelos de aprendizaje automático supervisado pueden aproximar la biodiversidad del suelo a partir de variables indirectas, relativamente más baratas y escalables que las obtenidas mendieta el muestreo directo.
